site_name: ADCIRC & SWAN Tutorials
site_author: Fuad Hasan
theme:
  name: material
  palette:
    primary: blue

nav:
  - Home: index.md

nav:
  - Home: index.md
  - Getting Started: tutorial 1.md
  - Resources to Learn: resources.md
  - Data sources: datasource.md
