site_name: ADCIRC & SWAN Tutorials

theme:
  name: material
  palette:
    primary: blue
    accent: cyan
  font:
    text: Roboto
  icon:
    logo: material/waves
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy
nav:
  - Home: index.md

nav:
  - Home: index.md
  - Getting Started: tutorial 1.md
  - Resources to Learn: resources.md
  - Data sources: datasource.md
  - ADCIRC Input Files: inputfiles.md
  - Mesh generation: mesh.md